- name: Install yum utils
  yum:
     name: yum-utils
     state: present    

- name: Install remi repo.
  yum:
    name: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: Import remi GPG key.
  rpm_key:
    key: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
    state: present


- name: enable remi-php repo
  shell: "yum-config-manager --enable remi-php{{ nginx_php_remi_version }}"


- name: Install php and fpm-php modules
  yum: 
    state: present 
    name: "{{ nginx_php_packages }}"

- name: config php
  include_tasks: 'config-php.yml'