---
- name: Install epel
  yum:
     name: epel-release
     state: present   
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

# set distribution variables
- name: set centos variables
  set_fact:
    nginx_user: "nginx"
    nginx_user_group: "nginx"
    nginx_phpfpm_conf_path: "/etc/php-fpm.d/www.conf"
    nginx_phpfpm_service_name: "php-fpm"
    nginx_php_ini_path: "/etc/php.ini"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: set debian 10 variables
  set_fact:
    nginx_user: "www-data"
    nginx_user_group: "www-data"
    nginx_phpfpm_conf_path: "/etc/php/7.3/fpm/pool.d/www.conf"
    nginx_phpfpm_service_name: "php7.3-fpm"
    nginx_php_ini_path: "/etc/php/7.3/fpm/php.ini"
  when: ansible_distribution == 'Debian'

# tasks file for nginx-php
- name: Install nginx
  package: 
    state: present 
    name: nginx

- name: install php
  include_tasks: 'install-php.yml'
  when: nginx_install_php and not nginx_php_ius and not nginx_php_remi

- name: install php ius
  include_tasks: 'install-php-ius.yml'
  when: nginx_install_php and nginx_php_ius and not nginx_php_remi

- name: install php remi
  include_tasks: 'install-php-remi.yml'
  when: nginx_install_php and nginx_php_remi and not nginx_php_ius

- name: configure nginx.conf
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    force: true
    owner: root
    group: root
    mode: 0644
  with_items: "{{ nginx_default }}"

- name: configure vhosts
  include_tasks: 'configure-vhosts.yml'
  when: nginx_vhosts is defined

- name: service nginx
  service:
    name: nginx
    state: restarted
    enabled: yes  

- include: 'security-redhat.yml'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'