---
# tasks file for nginx-php
- name: Install nginx
  yum: 
    state: present 
    name: "{{ item }}"
  with_items:
    - nginx

- name: install php
  include_tasks: 'install-php.yml'
  when: nginx_install_php and not nginx_php_ius

- name: install php ius
  include_tasks: 'install-php-ius.yml'
  when: nginx_install_php and nginx_php_ius

- name: service nginx
  service:
    name: nginx
    state: restarted
    enabled: yes  

- name: disable selinux
  selinux:
    state: disabled

- name: Install firewalld
  yum: 
    state: present 
    name: firewalld

- name: Enable and start firewalld
  service: 
    name: firewalld 
    state: started 
    enabled: yes

- name: enable firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled  
  notify: restarted firewalld   
  with_items: 
    "{{ nginx_firewall_ports }}"